### ISSUE TITLE
REF_DIR  

### ISSUE THREAD

**Issue by WWz33** [alexploner/cfdr.pleio#1]
Hello，
this site does not support breakpoints, I would be very grateful if it could be improved
https://github.com/alexploner/cfdr.pleio/blob/3d84ef97bbab10045d01e8690dfac54dfc4c8c11/vignettes/Introduction.Rmd.orig#L39

**Comment by alexploner** [comment]
Irrelevant (not a site), unclear (what is a breakpoint in this context?) and not actionable ("improved" how or why)

**Comment by WWz33** [comment]
> Irrelevant (not a site), unclear (what is a breakpoint in this context?) and not actionable ("improved" how or why)
https://github.com/alexploner/cfdr.pleio/blob/3d84ef97bbab10045d01e8690dfac54dfc4c8c11/vignettes/Introduction.Rmd.orig#L42
This website does not support file Resume Transfer Protocol(breakpoint),which has resulted in multiple failures during my attempts to download the file. I would like to upload it to websites like Google Drive.
In addition, I apologize for any lack of clarity in my explanation.
